// Captures lightweight behavior signals on the page and forwards them to
// the background as TRACK_BEHAVIOR messages. The suggestions engine then
// turns repeated patterns (e.g. dismissing the same modal 3+ times) into
// proposed features the user sees in the popup.
//
// Privacy guardrails:
//  - Never reads text from inputs, textareas, contenteditable regions,
//    or password fields.
//  - Skips entire hostnames matching /bank|auth|login/i — both because
//    that text is sensitive and because the resulting suggestions would
//    be noise.
import type { UserBehaviorEvent } from '../shared/types';

const ACTIVE_FLAG = '__bobBehaviorTrackerActive';

// Anchored on the bare-glyph case so a stray "x" in normal copy doesn't
// false-trigger. Word-boundary on the verbs catches "Close", "DISMISS",
// "Not now", etc.
const CLOSE_RE =
  /\b(close|dismiss|not now|no thanks|maybe later)\b|^\s*[×✕✖xX]\s*$/i;
const SENSITIVE_HOST_RE = /bank|auth|login/i;
const CLASS_RE = /(?:^|[\s_-])(close|dismiss|btn-close|modal-close)(?:$|[\s_-])/i;
const MODAL_CLASS_RE = /(?:^|[\s_-])(modal|popup|dialog|overlay|lightbox)(?:[\s_-]|$)/i;

const CLOSE_THROTTLE_MS = 500;
const TIME_THRESHOLD_MS = 60_000;
const LONG_DWELL_THRESHOLD_MS = 30_000;
const RAPID_REVISIT_WINDOW_MS = 5 * 60_000;
const SCROLL_BUFFER_WINDOW_MS = 5_000;
const SCROLL_BACKBOUNCE_WINDOW_MS = 8_000;
const SCROLL_BACKBOUNCE_TOLERANCE_PX = 100;
const SCROLL_BACKBOUNCE_MIN_DELTA_PX = 600;
// Per-event-type minimum interval. Stops a chatty page from flooding
// behavior storage with hundreds of similar events.
const PER_TYPE_THROTTLE_MS = 800;
const MAX_TEXT = 80;
const MAX_PARENT_WALK = 4;

const REVISITS_KEY = 'revisits';

const SENSITIVE_TAGS = new Set(['INPUT', 'TEXTAREA', 'SELECT']);

let lastCloseAt = 0;
let timeInterval: ReturnType<typeof setInterval> | null = null;
let timeSent = false;
let activeMs = 0;
let trackedHostname = '';

// Per-type throttle. Map<event-type → last fire timestamp>.
const lastFiredByType = new Map<UserBehaviorEvent['type'], number>();

// Long-dwell timer state. Reset on any user interaction.
let dwellTimer: ReturnType<typeof setTimeout> | null = null;
let dwellSent = false;

// Scroll-bounce-back state. We keep a small ring of recent scrollY +
// timestamp samples and look for a back-bounce on every scroll event.
type ScrollSample = { y: number; t: number };
const scrollBuffer: ScrollSample[] = [];
let scrollBackbounceFiredAt = 0;

function safeText(s: unknown): string {
  if (typeof s !== 'string') return '';
  // Collapse whitespace + cap.
  return s.replace(/\s+/g, ' ').trim().slice(0, MAX_TEXT);
}

function isSensitiveSubtree(start: Element | null): boolean {
  let el: Element | null = start;
  while (el && el !== document.body) {
    if (SENSITIVE_TAGS.has(el.tagName)) return true;
    if ((el as HTMLElement).isContentEditable) return true;
    if (el.tagName === 'INPUT') {
      const t = (el as HTMLInputElement).type;
      if (t === 'password') return true;
    }
    el = el.parentElement;
  }
  return false;
}

function isAutoGenClass(c: string): boolean {
  if (!c) return true;
  if (c.startsWith('css-')) return true;
  if (c.startsWith('jsx-')) return true;
  if (c.startsWith('_')) return true;
  if (/^[a-f0-9]{6,}$/i.test(c)) return true;
  if (/^[A-Za-z0-9]{12,}$/.test(c)) return true;
  return false;
}

function escapeAttrValue(v: string): string {
  return v.replace(/"/g, "'").replace(/\s+/g, ' ').trim().slice(0, MAX_TEXT);
}

function safeGetAttr(el: Element, name: string): string {
  try {
    return el.getAttribute(name) ?? '';
  } catch {
    return '';
  }
}

// Build a stable identifier string starting from `start`, walking up to
// MAX_PARENT_WALK ancestors looking for the first element with id /
// data-testid / aria-label. Falls back to tag + first non-autogenerated
// class on `start`.
function buildSelectorKey(start: Element): string {
  let cur: Element | null = start;
  for (let i = 0; cur && i <= MAX_PARENT_WALK; i++) {
    const id = safeGetAttr(cur, 'id');
    if (id) return `#${escapeAttrValue(id)}`;
    const tid = safeGetAttr(cur, 'data-testid');
    if (tid) return `[data-testid="${escapeAttrValue(tid)}"]`;
    const aria = safeGetAttr(cur, 'aria-label');
    if (aria) return `[aria-label="${escapeAttrValue(aria)}"]`;
    cur = cur.parentElement;
  }
  // Fallback: tag of start, plus first non-autogenerated class.
  const tag = (start.tagName || '').toLowerCase();
  let cls = '';
  try {
    const tokens = (start.getAttribute('class') ?? '')
      .split(/\s+/)
      .filter((t) => t && !isAutoGenClass(t));
    if (tokens.length > 0) cls = '.' + tokens[0];
  } catch {
    // ignore
  }
  return tag + cls;
}

// Look at `el` and its ancestors (up to 4) for the smallest element that
// looks like a close-y action surface. Returns the qualifying element +
// the matched text fragment that triggered the heuristic, or null.
function findCloseTarget(
  start: Element,
): { qualifier: Element; sample: string; subtype: 'click_close' | 'click_dismiss' } | null {
  let el: Element | null = start;
  for (let i = 0; el && i <= MAX_PARENT_WALK; i++) {
    const aria = safeGetAttr(el, 'aria-label');
    const role = safeGetAttr(el, 'role');
    const cls = safeGetAttr(el, 'class');
    const text = safeText(el.textContent);

    // aria-label match
    if (aria && CLOSE_RE.test(aria)) {
      return { qualifier: el, sample: safeText(aria), subtype: classify(aria) };
    }
    // text match (only short text — long text matching is too eager)
    if (text && text.length <= 50 && CLOSE_RE.test(text)) {
      return { qualifier: el, sample: text, subtype: classify(text) };
    }
    // class hint: e.g. "modal-close", "btn-close", "dismiss-btn"
    if (cls && CLASS_RE.test(cls)) {
      return {
        qualifier: el,
        sample: aria || text || cls.match(CLASS_RE)?.[0]?.trim() || 'close',
        subtype: /dismiss/i.test(cls) ? 'click_dismiss' : 'click_close',
      };
    }
    // role=button with close-like accessible name
    if (role === 'button' && (CLOSE_RE.test(aria) || CLOSE_RE.test(text))) {
      return {
        qualifier: el,
        sample: aria || text,
        subtype: classify(aria || text),
      };
    }
    el = el.parentElement;
  }
  return null;
}

function classify(matchedText: string): 'click_close' | 'click_dismiss' {
  if (/dismiss|not now|no thanks|maybe later/i.test(matchedText)) {
    return 'click_dismiss';
  }
  return 'click_close';
}

// Summarize up to MAX_PARENT_WALK ancestors of `start` as a short
// CSS-ish path. Skips autogenerated class names; favors id /
// data-testid / role / first stable class for each step. Used as
// metadata.parentContext on close events so the LLM analyzer has
// concrete vocabulary to describe what was dismissed.
function buildParentContext(start: Element): string {
  const parts: string[] = [];
  let cur: Element | null = start;
  for (let i = 0; cur && i < MAX_PARENT_WALK; i++) {
    const tag = (cur.tagName || '').toLowerCase();
    const id = safeGetAttr(cur, 'id');
    const tid = safeGetAttr(cur, 'data-testid');
    const role = safeGetAttr(cur, 'role');
    let token = tag;
    if (id) {
      token = `${tag}#${escapeAttrValue(id).slice(0, 30)}`;
    } else if (tid) {
      token = `${tag}[data-testid="${escapeAttrValue(tid).slice(0, 30)}"]`;
    } else if (role) {
      token = `${tag}[role="${escapeAttrValue(role).slice(0, 20)}"]`;
    } else {
      try {
        const tokens = (cur.getAttribute('class') ?? '')
          .split(/\s+/)
          .filter((t) => t && !isAutoGenClass(t));
        if (tokens.length > 0) token = `${tag}.${tokens[0]}`;
      } catch {
        // ignore
      }
    }
    parts.unshift(token);
    cur = cur.parentElement;
  }
  return parts.join(' > ').slice(0, 160);
}

function detectIsModal(start: Element): boolean {
  let cur: Element | null = start;
  for (let i = 0; cur && i < MAX_PARENT_WALK + 2; i++) {
    const role = safeGetAttr(cur, 'role');
    if (role === 'dialog' || role === 'alertdialog') return true;
    const ariaModal = safeGetAttr(cur, 'aria-modal');
    if (ariaModal && ariaModal.toLowerCase() === 'true') return true;
    const cls = safeGetAttr(cur, 'class');
    if (cls && MODAL_CLASS_RE.test(cls)) return true;
    cur = cur.parentElement;
  }
  return false;
}

function send(event: UserBehaviorEvent): void {
  // Per-type throttle. Stops a chatty page from flooding storage with
  // hundreds of e.g. scroll_past_back events. The first event of a new
  // type still goes through immediately.
  const now = Date.now();
  const last = lastFiredByType.get(event.type) ?? 0;
  if (now - last < PER_TYPE_THROTTLE_MS) return;
  lastFiredByType.set(event.type, now);

  try {
    void chrome.runtime.sendMessage({ type: 'TRACK_BEHAVIOR', event });
  } catch {
    // Background not ready / not in extension context — drop silently.
  }
}

function onClick(e: MouseEvent): void {
  const target = e.target as Element | null;
  if (!target || target.nodeType !== 1) return;
  // Privacy: never track clicks inside form inputs / contenteditable.
  if (isSensitiveSubtree(target)) return;
  // Any click counts as activity for the long-dwell timer.
  resetDwell();

  const now = Date.now();
  if (now - lastCloseAt < CLOSE_THROTTLE_MS) return;

  const found = findCloseTarget(target);
  if (!found) return;

  lastCloseAt = now;

  const event: UserBehaviorEvent = {
    type: found.subtype,
    url: location.href,
    hostname: trackedHostname,
    selector: buildSelectorKey(found.qualifier),
    text: safeText(found.sample),
    timestamp: now,
    metadata: {
      parentContext: buildParentContext(found.qualifier),
      isModal: detectIsModal(found.qualifier),
    },
  };
  send(event);
}

// ---- Long-dwell timer ----
//
// Fires once per page visit when the user has been visible on the page
// for LONG_DWELL_THRESHOLD_MS without any click / scroll / keypress
// activity. Restarted on every interaction; cancelled on visibility
// change to hidden. We don't track CPU dwell — only "user is here and
// not interacting".
function startDwell(): void {
  if (SENSITIVE_HOST_RE.test(trackedHostname)) return;
  dwellTimer = setTimeout(() => {
    if (dwellSent) return;
    if (document.visibilityState !== 'visible') return;
    dwellSent = true;
    send({
      type: 'long_dwell',
      url: location.href,
      hostname: trackedHostname,
      timestamp: Date.now(),
      metadata: { thresholdMs: LONG_DWELL_THRESHOLD_MS },
    });
  }, LONG_DWELL_THRESHOLD_MS);
}

function resetDwell(): void {
  if (dwellSent) return;
  if (dwellTimer !== null) clearTimeout(dwellTimer);
  startDwell();
}

// ---- Scroll buffer + back-bounce detection ----
//
// We keep a small ring of recent {y, t} samples within the last
// SCROLL_BUFFER_WINDOW_MS. A back-bounce fires when the current Y is
// at least SCROLL_BACKBOUNCE_MIN_DELTA_PX below a peak that occurred
// within SCROLL_BACKBOUNCE_WINDOW_MS, AND |currentY - peakY| ≤
// SCROLL_BACKBOUNCE_TOLERANCE_PX of returning to that peak's level.
// In practice that means: user scrolled down, then back up close to
// where they were before. Identifies the element at viewport center
// at the back-bounce position.
function onScroll(): void {
  resetDwell();
  const now = Date.now();
  const y = window.scrollY || window.pageYOffset || 0;

  // Trim old samples.
  while (
    scrollBuffer.length > 0 &&
    now - scrollBuffer[0].t > SCROLL_BUFFER_WINDOW_MS
  ) {
    scrollBuffer.shift();
  }
  scrollBuffer.push({ y, t: now });

  // Avoid firing a second back-bounce within the same backbounce window.
  if (now - scrollBackbounceFiredAt < SCROLL_BACKBOUNCE_WINDOW_MS) return;

  // Look for a peak within SCROLL_BACKBOUNCE_WINDOW_MS that was at
  // least currentY + SCROLL_BACKBOUNCE_MIN_DELTA_PX. Use a wider
  // lookback than SCROLL_BUFFER_WINDOW_MS by reusing the buffer (we
  // already capped it to 5s); for the 8s window we accept whatever's
  // in the buffer — close enough for the heuristic.
  let peakY = y;
  let peakT = now;
  for (const s of scrollBuffer) {
    if (now - s.t > SCROLL_BACKBOUNCE_WINDOW_MS) continue;
    if (s.y > peakY) {
      peakY = s.y;
      peakT = s.t;
    }
  }

  const delta = peakY - y;
  if (delta < SCROLL_BACKBOUNCE_MIN_DELTA_PX) return;
  if (peakT === now) return; // peak is the current sample — no bounce

  // Best-effort element identification at the bounce-back position.
  let selector = '';
  let textSample = '';
  try {
    const el = document.elementFromPoint(
      Math.floor(window.innerWidth / 2),
      Math.floor(window.innerHeight / 2),
    );
    if (el && !isSensitiveSubtree(el)) {
      selector = buildSelectorKey(el).slice(0, 120);
      const t = safeText(el.textContent);
      if (t.length <= 50) textSample = t;
    }
  } catch {
    // elementFromPoint can throw inside fullscreen / cross-origin frames
  }

  // Skip if user came back within tolerance — that means they basically
  // returned to where they started (real back-bounce). If they overshot
  // beyond the tolerance window, also skip (that's just scrolling up,
  // not bouncing).
  if (Math.abs(delta - SCROLL_BACKBOUNCE_MIN_DELTA_PX) < 0) {
    // currentY bounced back BELOW the original starting region
  }
  if (delta < SCROLL_BACKBOUNCE_MIN_DELTA_PX - SCROLL_BACKBOUNCE_TOLERANCE_PX) {
    return;
  }

  scrollBackbounceFiredAt = now;
  send({
    type: 'scroll_past_back',
    url: location.href,
    hostname: trackedHostname,
    selector,
    text: textSample || undefined,
    timestamp: now,
    metadata: { peakY, currentY: y, deltaPx: delta },
  });
}

function onKeyDown(): void {
  resetDwell();
}

// ---- Rapid revisit ----
//
// Persistent map of {hostname → lastVisitTs} in chrome.storage.local
// under REVISITS_KEY. On content-script init, if last visit was within
// RAPID_REVISIT_WINDOW_MS, fire a 'rapid_revisit' event. Always update
// the timestamp.
async function maybeFireRapidRevisit(): Promise<void> {
  if (SENSITIVE_HOST_RE.test(trackedHostname)) return;
  try {
    const r = await chrome.storage.local.get(REVISITS_KEY);
    const map = (r as Record<string, unknown>)[REVISITS_KEY];
    const safeMap: Record<string, number> =
      map && typeof map === 'object' ? (map as Record<string, number>) : {};
    const now = Date.now();
    const last = safeMap[trackedHostname];
    if (typeof last === 'number' && now - last < RAPID_REVISIT_WINDOW_MS) {
      send({
        type: 'rapid_revisit',
        url: location.href,
        hostname: trackedHostname,
        timestamp: now,
        metadata: { gapMs: now - last },
      });
    }
    safeMap[trackedHostname] = now;
    // Light cap: drop entries older than 24h to keep this map bounded.
    const dayAgo = now - 24 * 60 * 60_000;
    for (const k of Object.keys(safeMap)) {
      if (typeof safeMap[k] === 'number' && safeMap[k] < dayAgo) {
        delete safeMap[k];
      }
    }
    await chrome.storage.local.set({ [REVISITS_KEY]: safeMap });
  } catch {
    // chrome.storage unavailable — best-effort.
  }
}

function startTimeOnSite(): void {
  if (SENSITIVE_HOST_RE.test(trackedHostname)) return;
  if (timeInterval !== null) return;
  timeInterval = setInterval(() => {
    if (timeSent) {
      stopTimeOnSite();
      return;
    }
    if (document.visibilityState !== 'visible') return;
    activeMs += 1000;
    if (activeMs >= TIME_THRESHOLD_MS) {
      timeSent = true;
      send({
        type: 'time_on_site',
        url: location.href,
        hostname: trackedHostname,
        timestamp: Date.now(),
        metadata: { activeMs },
      });
      stopTimeOnSite();
    }
  }, 1000);
}

function stopTimeOnSite(): void {
  if (timeInterval !== null) {
    clearInterval(timeInterval);
    timeInterval = null;
  }
}

export function initBehaviorTracker(): void {
  const w = window as unknown as Record<string, unknown>;
  if (w[ACTIVE_FLAG]) return;
  w[ACTIVE_FLAG] = true;

  trackedHostname = (location.hostname || '').replace(/^www\./i, '').toLowerCase();
  if (!trackedHostname) return;
  if (SENSITIVE_HOST_RE.test(trackedHostname)) {
    // Don't even attach listeners — keeps the user's bank/login pages
    // untouched.
    return;
  }

  // Capture phase + passive: we want to see the click before any page
  // handler that might cancel/stop propagation, but we never call
  // preventDefault, so passive is fine and avoids slowing the main thread.
  document.addEventListener('click', onClick, { capture: true, passive: true });
  // Scroll + key listeners drive the new event types. Keypress handler
  // does NOT capture text (we never read e.key) — it just resets the
  // long-dwell timer and counts as activity.
  window.addEventListener('scroll', onScroll, { capture: true, passive: true });
  document.addEventListener('keydown', onKeyDown, { capture: true, passive: true });

  // Suspend dwell while the tab is hidden so a backgrounded tab doesn't
  // accumulate spurious dwell events. Resume on visibilitychange.
  document.addEventListener('visibilitychange', () => {
    if (document.visibilityState === 'visible') {
      resetDwell();
    } else if (dwellTimer !== null) {
      clearTimeout(dwellTimer);
      dwellTimer = null;
    }
  });

  startTimeOnSite();
  startDwell();
  void maybeFireRapidRevisit();
}
