// Captures lightweight behavior signals on the page and forwards them to
// the background as TRACK_BEHAVIOR messages. The suggestions engine then
// turns repeated patterns (e.g. dismissing the same modal 3+ times) into
// proposed features the user sees in the popup.
//
// Privacy guardrails:
//  - Never reads text from inputs, textareas, contenteditable regions,
//    or password fields.
//  - Skips entire hostnames matching /bank|auth|login/i — both because
//    that text is sensitive and because the resulting suggestions would
//    be noise.
import type { UserBehaviorEvent } from '../shared/types';

const ACTIVE_FLAG = '__bobBehaviorTrackerActive';

// Anchored on the bare-glyph case so a stray "x" in normal copy doesn't
// false-trigger. Word-boundary on the verbs catches "Close", "DISMISS",
// "Not now", etc.
const CLOSE_RE =
  /\b(close|dismiss|not now|no thanks|maybe later)\b|^\s*[×✕✖xX]\s*$/i;
const SENSITIVE_HOST_RE = /bank|auth|login/i;
const CLASS_RE = /(?:^|[\s_-])(close|dismiss|btn-close|modal-close)(?:$|[\s_-])/i;

const CLOSE_THROTTLE_MS = 500;
const TIME_THRESHOLD_MS = 60_000;
const MAX_TEXT = 80;
const MAX_PARENT_WALK = 4;

const SENSITIVE_TAGS = new Set(['INPUT', 'TEXTAREA', 'SELECT']);

let lastCloseAt = 0;
let timeInterval: ReturnType<typeof setInterval> | null = null;
let timeSent = false;
let activeMs = 0;
let trackedHostname = '';

function safeText(s: unknown): string {
  if (typeof s !== 'string') return '';
  // Collapse whitespace + cap.
  return s.replace(/\s+/g, ' ').trim().slice(0, MAX_TEXT);
}

function isSensitiveSubtree(start: Element | null): boolean {
  let el: Element | null = start;
  while (el && el !== document.body) {
    if (SENSITIVE_TAGS.has(el.tagName)) return true;
    if ((el as HTMLElement).isContentEditable) return true;
    if (el.tagName === 'INPUT') {
      const t = (el as HTMLInputElement).type;
      if (t === 'password') return true;
    }
    el = el.parentElement;
  }
  return false;
}

function isAutoGenClass(c: string): boolean {
  if (!c) return true;
  if (c.startsWith('css-')) return true;
  if (c.startsWith('jsx-')) return true;
  if (c.startsWith('_')) return true;
  if (/^[a-f0-9]{6,}$/i.test(c)) return true;
  if (/^[A-Za-z0-9]{12,}$/.test(c)) return true;
  return false;
}

function escapeAttrValue(v: string): string {
  return v.replace(/"/g, "'").replace(/\s+/g, ' ').trim().slice(0, MAX_TEXT);
}

function safeGetAttr(el: Element, name: string): string {
  try {
    return el.getAttribute(name) ?? '';
  } catch {
    return '';
  }
}

// Build a stable identifier string starting from `start`, walking up to
// MAX_PARENT_WALK ancestors looking for the first element with id /
// data-testid / aria-label. Falls back to tag + first non-autogenerated
// class on `start`.
function buildSelectorKey(start: Element): string {
  let cur: Element | null = start;
  for (let i = 0; cur && i <= MAX_PARENT_WALK; i++) {
    const id = safeGetAttr(cur, 'id');
    if (id) return `#${escapeAttrValue(id)}`;
    const tid = safeGetAttr(cur, 'data-testid');
    if (tid) return `[data-testid="${escapeAttrValue(tid)}"]`;
    const aria = safeGetAttr(cur, 'aria-label');
    if (aria) return `[aria-label="${escapeAttrValue(aria)}"]`;
    cur = cur.parentElement;
  }
  // Fallback: tag of start, plus first non-autogenerated class.
  const tag = (start.tagName || '').toLowerCase();
  let cls = '';
  try {
    const tokens = (start.getAttribute('class') ?? '')
      .split(/\s+/)
      .filter((t) => t && !isAutoGenClass(t));
    if (tokens.length > 0) cls = '.' + tokens[0];
  } catch {
    // ignore
  }
  return tag + cls;
}

// Look at `el` and its ancestors (up to 4) for the smallest element that
// looks like a close-y action surface. Returns the qualifying element +
// the matched text fragment that triggered the heuristic, or null.
function findCloseTarget(
  start: Element,
): { qualifier: Element; sample: string; subtype: 'click_close' | 'click_dismiss' } | null {
  let el: Element | null = start;
  for (let i = 0; el && i <= MAX_PARENT_WALK; i++) {
    const aria = safeGetAttr(el, 'aria-label');
    const role = safeGetAttr(el, 'role');
    const cls = safeGetAttr(el, 'class');
    const text = safeText(el.textContent);

    // aria-label match
    if (aria && CLOSE_RE.test(aria)) {
      return { qualifier: el, sample: safeText(aria), subtype: classify(aria) };
    }
    // text match (only short text — long text matching is too eager)
    if (text && text.length <= 50 && CLOSE_RE.test(text)) {
      return { qualifier: el, sample: text, subtype: classify(text) };
    }
    // class hint: e.g. "modal-close", "btn-close", "dismiss-btn"
    if (cls && CLASS_RE.test(cls)) {
      return {
        qualifier: el,
        sample: aria || text || cls.match(CLASS_RE)?.[0]?.trim() || 'close',
        subtype: /dismiss/i.test(cls) ? 'click_dismiss' : 'click_close',
      };
    }
    // role=button with close-like accessible name
    if (role === 'button' && (CLOSE_RE.test(aria) || CLOSE_RE.test(text))) {
      return {
        qualifier: el,
        sample: aria || text,
        subtype: classify(aria || text),
      };
    }
    el = el.parentElement;
  }
  return null;
}

function classify(matchedText: string): 'click_close' | 'click_dismiss' {
  if (/dismiss|not now|no thanks|maybe later/i.test(matchedText)) {
    return 'click_dismiss';
  }
  return 'click_close';
}

function send(event: UserBehaviorEvent): void {
  try {
    void chrome.runtime.sendMessage({ type: 'TRACK_BEHAVIOR', event });
  } catch {
    // Background not ready / not in extension context — drop silently.
  }
}

function onClick(e: MouseEvent): void {
  const target = e.target as Element | null;
  if (!target || target.nodeType !== 1) return;
  // Privacy: never track clicks inside form inputs / contenteditable.
  if (isSensitiveSubtree(target)) return;

  const now = Date.now();
  if (now - lastCloseAt < CLOSE_THROTTLE_MS) return;

  const found = findCloseTarget(target);
  if (!found) return;

  lastCloseAt = now;

  const event: UserBehaviorEvent = {
    type: found.subtype,
    url: location.href,
    hostname: trackedHostname,
    selector: buildSelectorKey(found.qualifier),
    text: safeText(found.sample),
    timestamp: now,
  };
  send(event);
}

function startTimeOnSite(): void {
  if (SENSITIVE_HOST_RE.test(trackedHostname)) return;
  if (timeInterval !== null) return;
  timeInterval = setInterval(() => {
    if (timeSent) {
      stopTimeOnSite();
      return;
    }
    if (document.visibilityState !== 'visible') return;
    activeMs += 1000;
    if (activeMs >= TIME_THRESHOLD_MS) {
      timeSent = true;
      send({
        type: 'time_on_site',
        url: location.href,
        hostname: trackedHostname,
        timestamp: Date.now(),
        metadata: { activeMs },
      });
      stopTimeOnSite();
    }
  }, 1000);
}

function stopTimeOnSite(): void {
  if (timeInterval !== null) {
    clearInterval(timeInterval);
    timeInterval = null;
  }
}

export function initBehaviorTracker(): void {
  const w = window as unknown as Record<string, unknown>;
  if (w[ACTIVE_FLAG]) return;
  w[ACTIVE_FLAG] = true;

  trackedHostname = (location.hostname || '').replace(/^www\./i, '').toLowerCase();
  if (!trackedHostname) return;
  if (SENSITIVE_HOST_RE.test(trackedHostname)) {
    // Don't even attach listeners — keeps the user's bank/login pages
    // untouched.
    return;
  }

  // Capture phase + passive: we want to see the click before any page
  // handler that might cancel/stop propagation, but we never call
  // preventDefault, so passive is fine and avoids slowing the main thread.
  document.addEventListener('click', onClick, { capture: true, passive: true });

  startTimeOnSite();
}
